crawler_class: examples.ai_lit_crawler.AILitCrawler

site_name: ai_lit
list_url: https://blogs.gwu.edu/law-eti/ai-litigation-database/?page={page}
list_selector: "table"      # the AILit parser looks for a table on the list pages

pagination:
  start_page: 1
  max_pages: 2

detail_selectors:
  title: "h1.entry-title"
  date: "time.published"
  summary: ".field--name-field-summary p"
  parties: ".field--name-field-parties p"
  court: ".field--name-field-court p"
  docket: ".field--name-field-docket p"

concurrency: 3
rate_limit: 1
output_path: data/ai_lit.csv
output_format: csv
