crawler_class: examples.climate_lit_crawler.ClimateLitCrawler

start_url: "https://climatecasechart.com/search/"
list_selector: "article"          # use a safe selector; avoid invalid patterns like "article.post-*.case_bundle"
detail_selectors:
  title: "h1.entry-title"
  filed_date: "div.field--name-field-filed span.highlight"
  status: "div.field--name-field-status span.highlight"
  court: "div.field--name-field-court span.highlight"
  description: "div.field--name-field-summary p"

concurrency: 2
rate_limit: 1

output_path: data/climate_cases.csv
output_format: csv

debug_page: data/debug_page1.html

pagination:
  start_page: 1
  max_pages: 1
